### PR TITLE
Chinese Translations And $,$$ support

### PR DESCRIPTION
**Pull request by AlongWY**
# Chinese Translations And $,$$ support

+ Chinese Translations
+ $,$$ Tex input support
+ \\( \\) , \\[ \\] input support

### CODE REVIEW

**Comment by hasan-ozbey** [comment]
Thank you! But... Code classes won't work with these new delimiters. I'm gonna merge it as soon as you fix it.

**Comment by AlongWY** [comment]
I find that [manthren] bbcode in \<code\> class is also be rendered. 
Do u think katex should ignore the [mathren] bbcode in \<code\> class when enableCode option is disabled?

**Comment by hasan-ozbey** [comment]
I'm sorry but i don't think you get the whole situation. When `enableCode` option is disabled, expression will be rendered _without the code tag_ around it. If you add new delimiters directly into KaTeX Auto-render extension's options:

1-) The `code` tag's `class` attribute's will be useless. Because of that, we will end up with a background color on all of the expressions. You can't change the way it looks and they will definitely not look the same with those written using `[mathren][/mathren]` or `[mathren-inline][/mathren-inline]` delimiters if you already stylized them with their special class names (`.mathren-code` & `.mathren-inline-code`).
2-) If you ignore the code tag by default, `enableCode` option will be meaningless. Because, you're already disabling it by using "Ignored tags" option. It just won't work.
3-) Ignored classes won't work with the new delimiters.
4-) There may be some users who doesn't want to use the new delimiters. It must be optionable and it's not.

Also you're using a long RegEx to find expressions. It seems very unreliable to me and i'm not comfortable with it. Auto-render extension is already finding the expressions to be rendered.

Again, sorry, but i have to close this for now. But you're welcome to open a new pull request for Chinese translation (please use ISO 639-1 or ISO 3166-1 alpha-2 country code as filename - see more on https://flarum.org/docs/extend/i18n.html#how-flarum-translates).

**Comment by hasan-ozbey** [comment]
0.2.0 released. Check if it suits for your needs.

**Pull request closed without merging**
